import "../styles/globals.css";
import Header from "../Components/Header";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Blog.png" />

          <link
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;500&display=swap"
            rel="stylesheet"
          />
          {/* <Script defer src="https://cdn.tailwindcss.com"/>npx tailwindcss init -p */}

          <script defer src="https://cdn.tailwindcss.com"></script>
          <title>Basic Blog App in Next JS</title>
        </Head>

      <Header />
        <Component {...pageProps} />
    </div>
  );
}

export default MyApp;
